### ISSUE TITLE
magrit-wait-for timeout server-side returning error code

### ISSUE THREAD

**Issue by daniperez** [ptitfred/magrit#12]
When I do magrit-wait-for and a timeout is used, ssh will end with a 2 return code, i.e. treating the timeout as an error condition. I think ssh is returning the return code of the command being executed.

Two questions: first, should the timeout be treated as an error? Second: shouldn't it be better if we treated the timeouts client side? (I'm shooting my own food since it's quite handy to let the server do that for me :-) ).

**Comment by ptitfred** [comment]
Exit code 2 stands for timeout and magrit-wait-for should exit with the same error code. The timeout handling can't be done in the scripts. Caller will know what to do (exit, retry or whatever).
